In [2]:
Stefano.Piani@sissa.it

NameError: name 'Stefano' is not defined

In [3]:
my_str = "Whatever"

for i in my_str:
    print(i)

W
h
a
t
e
v
e
r


In [4]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [5]:
my_sum = 0

for i in [1,2,3,4,5,6,7,8,9,10].
    my_sum+=i

SyntaxError: invalid syntax (<ipython-input-5-e3dcfd23b83e>, line 3)

In [6]:
my_sum = 0

for i in [1,2,3,4,5,6,7,8,9,10]:
    my_sum+=i

In [7]:
my_sum

55

In [8]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
my_container = range(10)
for i in my_container:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [10]:
for i in range(10,20):
    print(i)

10
11
12
13
14
15
16
17
18
19


In [11]:
for i in range(10,20,3):
    print(i)

10
13
16
19


In [12]:
i=1000
for i in range(10):
    print(i)
print()
print(i)

0
1
2
3
4
5
6
7
8
9

9


In [14]:
def strange_iterable():
    i=0
    while(i<100):
        if i%3 == 0 or i%5 ==0:
            yield i
        i=i+1
        
for i in strange_iterable():
    print(i)

0
3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50
51
54
55
57
60
63
65
66
69
70
72
75
78
80
81
84
85
87
90
93
95
96
99


In [16]:
for i in [1,3,5]: #this iterable is a list
    print(i)

1
3
5


In [17]:
a = [1,2,3]
a

[1, 2, 3]

In [18]:
a = ["banana",42,True,3.7]
a

['banana', 42, True, 3.7]

In [19]:
def f(x):
    return x*x

In [20]:
a = ['banana',f,True] #put a function inside a list

In [21]:
a

['banana', <function __main__.f>, True]

In [23]:
a[0]

'banana'

In [24]:
a[2]

True

In [25]:
a[0] = "apple"

In [26]:
a

['apple', <function __main__.f>, True]

In [27]:
my_str = "hello"
my_str[0] = 33

TypeError: 'str' object does not support item assignment

In [28]:
a.append("orange")

In [29]:
a

['apple', <function __main__.f>, True, 'orange']

In [30]:
a.remove("apple")
a

[<function __main__.f>, True, 'orange']

In [31]:
my_str = "hello"
my_str[2:4]

'll'

In [32]:
a

[<function __main__.f>, True, 'orange']

In [33]:
a[1:]

[True, 'orange']

In [35]:
a = [10,34, 2,-6,9,14,13]

In [41]:
a = [10,34,2,-6,9,14,3]
def only_greater_than(n,my_list):
    b = []
    for i in my_list:
        if i>n:
            b.append(i)
    return b

only_greater_than(12,a)

[34, 14]

In [42]:
import math

def square_root_of(my_list):
    b=[]
    for i in my_list:
        b.append(math.sqrt(i))
    return b

a = [1,4,9,16,25,7]
square_root_of(a)

[1.0, 2.0, 3.0, 4.0, 5.0, 2.6457513110645907]

In [45]:
from math import sqrt #do not import the whole library, just the functions you need!!
#functions work with namespaces

In [44]:
sqrt(4.)

2.0

In [46]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(...)
        acos(x)
        
        Return the arc cosine (measured in radians) of x.
    
    acosh(...)
        acosh(x)
        
        Return the inverse hyperbolic cosine of x.
    
    asin(...)
        asin(x)
        
        Return the arc sine (measured in radians) of x.
    
    asinh(...)
        asinh(x)
        
        Return the inverse hyperbolic sine of x.
    
    atan(...)
        atan(x)
        
        Return the arc tangent (measured in radians) of x.
    
    atan2(...)
        atan2(y, x)
        
        Return the arc tangent (measured in radians) of y/x.
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(...)
        atanh(x)
        
        Return the inverse hyperbolic tangent of x.
    
    ceil(...)
        ceil(x)
        
 

In [47]:
help(sqrt)

Help on built-in function sqrt in module math:

sqrt(...)
    sqrt(x)
    
    Return the square root of x.



In [49]:
from math import *
from numpy import *

help(sin) #sin() will be sin() of numpy

Help on ufunc object:

sin = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [50]:
a = [4,6,2,4,9,12,21]
sorted(a)

[2, 4, 4, 6, 9, 12, 21]

In [51]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [52]:
b = ["hello","goodbye","farewell","bye"]
sorted(b)

['bye', 'farewell', 'goodbye', 'hello']

In [53]:
b.append(99)
b
sorted(b)

TypeError: '<' not supported between instances of 'int' and 'str'

In [54]:
b = b[:-1]

In [55]:
b

['hello', 'goodbye', 'farewell', 'bye']

In [56]:
sorted(b,reverse=True)

['hello', 'goodbye', 'farewell', 'bye']

In [57]:
def how_long(x):
    return len(x)

sorted(b,key=how_long)

['bye', 'hello', 'goodbye', 'farewell']

In [58]:
sorted(b,key=len)

['bye', 'hello', 'goodbye', 'farewell']

In [62]:
lambda x: x*x #define function on the fly

<function __main__.<lambda>>

In [60]:
a=[-1,4,-9,3]
sorted(a,key=square)

[-1, 3, 4, -9]

In [61]:
a=[-1,4,-9,3]
sorted(a,key=lambda x: x*x)

[-1, 3, 4, -9]

In [2]:
def power(x,n):
    k = x
    for i in range(1,n):
        k *= x
    return k

power(3,3)

27

In [3]:
def power(x,n=2): #if I do not specify n, it is automatically 2
    k = x
    for i in range(1,n):
        k *= x
    return k

power(3)

9

In [7]:
def power(x,n=2,adding=0): #if I do not specify n, it is automatically 2
    k = x
    for i in range(1,n):
        k *= x
    k+=adding
    return k

power(5,2,7)

32

In [8]:
power(5,adding=9)

34

In [10]:
#Not performant way of doing the sum:
a = [1,2,3,4,5,6]
k = 0
for i in a:
    k+=i
print(k)

21


In [11]:
import numpy as np

In [12]:
a = np.empty(100,dtype=np.int32)

In [13]:
a

array([   19746160,           0, -1060151136,       32716, -1128712792,
             32716, -1060151136,       32716, -1128712848,       32716,
       -1060151136,       32716, -1128718424,       32716, -1060151136,
             32716, -1059804160,       32716, -1060151136,       32716,
       -1128712904,       32716, -1060151136,       32716, -1128712960,
             32716, -1060151136,       32716, -1128713016,       32716,
       -1060151136,       32716, -1128713072,       32716, -1060151136,
             32716, -1128713520,       32716, -1060151136,       32716,
       -1128713688,       32716, -1060151136,       32716, -1128713408,
             32716, -1060151136,       32716, -1128752144,       32716,
       -1060151136,       32716, -1128713632,       32716, -1060151136,
             32716, -1128713240,       32716, -1060151136,       32716,
       -1128713296,       32716, -1060151136,       32716, -1128713576,
             32716, -1128712344,       32716, -1058690384,      

In [14]:
from math import sqrt as whatever

In [15]:
whatever(16)

4.0

In [16]:
from sys import exit as sys_exit #not to overwrite the usual "exit"

In [17]:
#You cannot re-import things!

In [20]:
a = np.empty(100,dtype=np.int64)
my_number1 = np.int32(2500000000)
my_number2 = np.int32(2500000000)
print(my_number1)
my_number1 + my_number2

-1794967296


/usr/lib/python3/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in int_scalars
  """


705032704

In [21]:
my_number1 = np.uint32(2500000000)
my_number2 = np.uint32(2500000000)
print(my_number1)

2500000000


In [24]:
a = np.empty(10,dtype=np.float64)
for i in range(10):
    a[i] = i*i
a

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [26]:
b = a[3:7] #b is also a numpy array
b

array([ 9., 16., 25., 36.])

In [27]:
b[0] = "banana"

ValueError: could not convert string to float: 'banana'

In [28]:
b

array([ 9., 16., 25., 36.])

In [29]:
a

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [39]:
x = a
y = a

In [40]:
np.sqrt(x**2 + y**2)

array([  0.        ,   1.41421356,   5.65685425,  12.72792206,
        22.627417  ,  35.35533906,  50.91168825,  69.29646456,
        90.50966799, 114.55129855])

In [41]:
x - y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
a - b

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [43]:
a = np.zeros(10,dtype=np.float64)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
a = np.array([1,2,3,4,5,6],dtype=np.float64)
a

array([1., 2., 3., 4., 5., 6.])

In [46]:
a = np.zeros([10,10],dtype=np.float64)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
a = np.empty((3,10),dtype=np.float64) #if you do not specify, the type is float 64
a

array([[1.19985621e-316, 9.36293134e-317, 0.00000000e+000,
        0.00000000e+000, 1.97047186e-153, 4.82337433e+228,
        6.14415221e-144, 1.16097020e-028, 1.48340479e-076,
        4.17389626e-057],
       [5.05230740e-038, 3.97062373e+246, 1.16318408e-028,
        1.38267483e-047, 7.61352934e-042, 4.42701984e-062,
        9.30447352e+165, 5.04621361e+180, 8.37170571e-144,
        4.46705975e-143],
       [1.12855837e+277, 6.32672840e+180, 2.66371964e+233,
        2.16385138e+190, 2.87012909e+180, 1.00511886e-047,
        2.62398070e+179, 1.34751027e+165, 5.17559676e-143,
        2.28664860e-152]])

In [49]:
for i in range(10):
    a[0,i] = np.random.random()
    a[1,i] = np.random.random()
    a[2,i] = 0

In [50]:
mass = np.zeros(10)
for i in range(10):
    mass[i] = i

In [51]:
mass * a

array([[0.        , 0.10055547, 0.465054  , 1.26055376, 1.78581535,
        1.44714638, 1.61210661, 2.59551584, 7.75924489, 6.64490851],
       [0.        , 0.73410577, 0.85939253, 0.4253744 , 1.9702148 ,
        1.14086469, 5.15072265, 0.90556068, 2.12124491, 2.36800579],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [55]:
mass.shape # having a shape (10,) it is like (10,1)

(10,)

In [53]:
a.shape

(3, 10)

In [54]:
b = np.zeros([2,10])
a+b

ValueError: operands could not be broadcast together with shapes (3,10) (2,10) 

In [57]:
a + mass #mass is REPLICATED 3 times to be (3,10) and then does the sum (replicate the columns that you miss)

array([[0.14926031, 1.10055547, 2.232527  , 3.42018459, 4.44645384,
        5.28942928, 6.26868444, 7.37078798, 8.96990561, 9.73832317],
       [0.99325608, 1.73410577, 2.42969626, 3.14179147, 4.4925537 ,
        5.22817294, 6.85845378, 7.12936581, 8.26515561, 9.26311175],
       [0.        , 1.        , 2.        , 3.        , 4.        ,
        5.        , 6.        , 7.        , 8.        , 9.        ]])